// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl(): string {
  if (process.env["DATABASE_URL"]) {
    return process.env["DATABASE_URL"];
  }
  const host = process.env["DB_HOST"] ?? "localhost";
  const port = process.env["DB_PORT"] ?? "5432";
  const user = process.env["DB_USER"] ?? "postgres";
  const password = process.env["DB_PASSWORD"] ?? "";
  const dbName = process.env["DB_NAME"] ?? "vidwave";
  return `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@${host}:${port}/${dbName}?schema=public`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node prisma/seed.ts",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
